# Generated by Django 5.2 on 2025-05-28 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='depo',
            table='website_depo',
        ),
        migrations.AlterModelTable(
            name='product',
            table='website_product',
        ),
    ]
